// <auto-generated />
using K1P1.RowCounterBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace K1P1.RowCounterBot.Database.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("K1P1.RowCounterBot.Models.Counter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("RowCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "ChatId");

                    b.HasIndex("ChatId");

                    b.ToTable("Counters");
                });

            modelBuilder.Entity("K1P1.RowCounterBot.Models.StateMachine", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.ToTable("StateMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
